datasource:
  driver: "{{ svc.database.driver }}"
  conn: "{{ svc.database.conn }}"
interval: 1m
prometheus:
  address: "http://localhost:{{ prometheus.listeners.hikkabot }}/metrics"
telegram:
  token: "{{ telegram.tokens.hikkabot }}"
  supervisor: {{ telegram.supervisor_id }}
  aliases: {{ svc.aliases }}
media:
  directory: /tmp/{{ svc.name }}/media
  retries: 5
  curl: curl
dvach:
  usercode: "{{ svc.dvach.usercode }}"
reddit:
  clientid: "{{ svc.reddit.clientid }}"
  clientsecret: "{{ svc.reddit.clientsecret }}"
  username: "{{ svc.reddit.username }}"
  password: "{{ svc.reddit.password }}"
  maxretries: 3