datasource:
  driver: "{{ hikkabot.database.driver }}"
  conn: "{{ hikkabot.database.conn }}"
interval: 1m
prometheus:
  address: "http://localhost:{{ prometheus.listeners.hikkabot }}/metrics"
telegram:
  token: "{{ telegram.tokens.hikkabot }}"
  supervisor: {{ telegram.supervisor_id }}
  aliases: "{{ hikkabot.aliases }}"
media:
  directory: /tmp/{{ svc.name }}/media
  retries: 5
  curl: curl
dvach:
  usercode: "{{ hikkabot.dvach.usercode }}"
reddit:
  clientid: "{{ hikkabot.reddit.clientid }}"
  clientsecret: "{{ hikkabot.reddit.clientsecret }}"
  username: "{{ hikkabot.reddit.username }}"
  password: "{{ hikkabot.reddit.password }}"
  maxretries: 3