---
- hosts: "{{ host }}"
  become: yes
  vars:
    deb: https://www.process-one.net/downloads/downloads-action.php?file=/21.04/ejabberd_21.04-0_amd64.deb
    conf: /opt/ejabberd/conf
    svc: "{{ ejabberd }}"
    cert_name: "xmpp.{{ svc.host }}"
    certfiles:
      fullchain: "/etc/letsencrypt/live/{{ cert_name }}/fullchain.pem"
      privkey: "/etc/letsencrypt/live/{{ cert_name }}/privkey.pem"
  tasks:
  - name: install ejabberd
    apt: deb={{ deb }}
  - name: get public ip
    ipify_facts:
  - name: copy config
    template: src=ejabberd.yml dest={{ conf }} owner={{ svc.user }} group={{ svc.user }}
  - name: install certbot
    snap: name=certbot classic=yes
  - name: check that certfiles exist
    shell: >-
      /snap/bin/certbot certonly -n --nginx
      -d {{ svc.host }} 
      -d conference.{{ svc.host }} 
      -d proxy.{{ svc.host }}
      -d pubsub.{{ svc.host }}
      -d upload.{{ svc.host }}
      --cert-name {{ cert_name }}
      --agree-tos 
      --email {{ email }}
  - name: copy certfiles
    copy: remote_src=yes src={{ item.value }} dest={{ conf }} owner={{ svc.user }} group={{ svc.user }} mode=0600
    with_dict: "{{ certfiles }}"
  - name: restart service
    systemd: name=ejabberd daemon_reload=yes state=restarted