
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

switch:
  - name: PC
    platform: wake_on_lan
    host: {{ home.devices.pc.ip }}
    mac: {{ home.devices.pc.mac }}
  - platform: template
    switches:
      ac:
        friendly_name: AC
        unique_id: switch_ac
        value_template: >
          {{ '{{' }} 
            is_state('binary_sensor.contact_sensor', 'on') 
          {{ '}}' }}
        turn_on:
          service: script.turn_ac_on
        turn_off:
          service: script.turn_ac_off

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: {{ mount.external }}
      - type: memory_use_percent
      - type: load_1m
      - type: throughput_network_in
        arg: enp3s0
      - type: throughput_network_out
        arg: enp3s0
  - platform: template
    sensors:
      anybody_home:
        friendly_name: Anybody home
        unique_id: anybody_home
        value_template: >
          {{ '{{' }}
             is_state('person.igor', 'home') or is_state('person.julia', 'home') or
             is_state('device_tracker.igor_s_phone', 'home') or
             is_state('device_tracker.redmi_note_9_pro_2', 'home')
          {{ '}}' }}
      bad_weather:
        friendly_name: Bad weather
        unique_id: bad_weather
        value_template: >
          {{ '{{' }}
             states('weather.home') in (
               'hail', 'lightning', 'lightning-rainy',
               'pouring', 'rainy', 'snowy', 'snowy-rainy')
          {{ '}}' }}

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - ::1

shopping_list:

homeassistant:
  name: Home
  latitude: {{ home.geo.latitude }}
  longitude: {{ home.geo.longitude }}
  elevation: {{ home.geo.elevation }}
  unit_system: metric
  time_zone: {{ home.geo.time_zone }}
  external_url: "https://{{ svc.host }}"
  media_dirs:
    tv: {{ transmission.download_paths.tv }}
    movie: {{ transmission.download_paths.movies }}

media_source:

recorder:
  commit_interval: 60

