---
- hosts: "{{ chia.master }}"
  vars:
    svc: "{{ chia.exporter }}"
    svc_dir: "/opt/{{ svc.name }}"
    bin: "{{ svc_dir }}/{{ svc.name }}"
  tasks:
    - include_tasks: ../base/go.yml
    - include_tasks: ../base/logrotate.yml
    - include_tasks: ../base/supervisor.yml
