---
- hosts: "{{ host }}"
  vars:
    svc: "{{ syncthing }}"
    bin: syncthing
  tasks:
  - block:
    - name: install syncthing
      apt: package=syncthing
    - name: add {{ svc.user }} to {{ user }} group
      user:
        name: "{{ svc.user }}"
        groups: "{{ user }}"
        append: true
    become: true
  - include_tasks: ../base/logrotate.yml
  - include_tasks: ../base/supervisor.yml
  - include_tasks: ../nginx.yml