---
- hosts: "{{ host }}"
  vars:
    svc: "{{ transmission }}"
  tasks:
  - block:
    - name: install daemon
      apt: package=transmission-daemon
    - name: add debian-transsmission to {{ user }} group
      user:
        name: debian-transmission
        groups: "{{ user }}"
        append: true
    - name: create download directories
      file:
        path: "{{ item.value }}"
        state: directory
        mode: 0775
        owner: "{{ user }}"
        group: "{{ user }}"
      with_dict: "{{ svc.download_paths }}"
    - name: reload and stop daemon
      systemd:
        name: transmission-daemon
        state: stopped
        daemon_reload: true
    - name: update settings
      template:
        src: settings.json
        dest: /etc/transmission-daemon
        mode: 0600
        owner: debian-transmission
        group: debian-transmission
    - name: start daemon
      systemd:
        name: transmission-daemon
        state: started
    become: true
  - include_tasks: ../nginx.yml