---
- hosts: "{{ host }}"
  vars:
    svc: "{{ photoprism }}"
  tasks:
  - include_tasks: ../base/docker.yml
  - set_fact: storage_dir={{ svc_dir }}
  - include_tasks: ../nginx.yml
  - block:
    - name: precreate storage directory
      file: path={{ storage_dir }} state=directory owner={{ svc.user }} group={{ svc.user }}
    - name: start docker container
      docker_container:
        image: photoprism/photoprism
        name: "{{ svc.name }}"
        published_ports: "{{ svc.port }}:{{ svc.port }}"
        pull: yes
        restart: yes
        restart_policy: always
        state: started
        env_file: "{{ svc_dir }}/env"
        volumes: 
          - "{{ svc.originals }}:/originals"
          - "{{ storage_dir }}:/storage"
        working_dir: "{{ svc_dir }}"
    become: yes
  - name: add backup to cron
    cron:
      name: photoprism backup
      job: >
        BACKUP={{ mount.external }}/backup/photoprism;
        mkdir -p $BACKUP &&
        find $BACKUP -type f -mtime +30 -delete &&
        tar --exclude='{{ storage_dir }}/cache'
        -zcvf $BACKUP/$(date +'\%Y-\%m-\%d').tar.gz {{ storage_dir }}
      minute: "0"
      hour: "11"
    become: yes
    become_user: "{{ svc.user }}"
